Repository f-lab-edu/Find_Your_Character_GPT, pull requests merged in 2023-07, with the labels that each got.

#62 Issue 60 main routing 수정
  src/app/page.tsx
  src/app/stage/page.tsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/components/floatButton/StartButton.tsx
  src/pages/api/generate.tsx
Labels: 🔨 Refactor

#59 Issue 54 Prompt수정
  src/pages/api/generate.tsx
Labels: 📬 API, ✨ Feature

#65 Issue 63 question 내용 수정
  src/question.json
Labels: ✨ Feature

#66 Issue 64 수정된 question에 맞게 prompt 수정
  src/pages/api/generate.tsx
Labels: 📬 API, 🔨 Refactor

#68 Issue 67 loading창 구현
  src/app/stage/page.tsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/pages/api/generate.tsx
Labels: ✨ Feature

#72 Issue 71 멘토링 수정사항 반영
  src/components/GameDesc/GameDescBox.tsx
  src/pages/api/generate.tsx
  src/question.json
Labels: 🐞 BugFix

#74 Issue 73 prompt 에러 수정
  src/components/GameDesc/GameDescBox.tsx
  src/pages/api/generate.tsx
Labels: 📬 API, 🐞 BugFix

#76 Issue 75 gpt통신 시 틀린 stage result값으로 통신하는 에러
  src/app/stage/page.tsx
  src/components/GameDesc/GameDescBox.tsx
Labels: 📬 API, 🐞 BugFix

#80 Fix: kakao type 에러 수정
  next-env.d.ts
  package-lock.json
  package.json
  src/components/shareModal/ShareModal.tsx
  window.d.ts
Labels: 🐞 BugFix

#81 Issue 70 app, document 설정
  src/app/_app.tsx
  src/app/layout.tsx
  src/pages/_document.tsx
Labels: ✨ Feature

#83 Issue 82 component렌더링 과정에서 상태변경되는 에러 수정
  src/components/GameDesc/GameDescBox.tsx
Labels: 🐞 BugFix

#86 Issue 85 font설정이 안되는 문제 해결
  src/app/layout.tsx
  src/pages/_document.tsx
Labels: 🐞 BugFix

#87 Issue 1 Readme 작성
  README.md
Labels: 📄Docs

#88 Issue 84 GPTHandler코드 위치 변경
  src/app/result/page.tsx
  src/app/stage/page.tsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/pages/api/generate.tsx
Labels: 🔨 Refactor

#91 Issue 46 F-lab로고 추가
  public/img/logo.svg
  src/app/page.tsx
  src/components/SponsorMessage/SponsorMessage.tsx
Labels: ✨ Feature

#94 Issue 93 F-Lab로고 클릭시 새로운 탭 열리도록 수정
  src/components/SponsorMessage/SponsorMessage.tsx
Labels: 🔨 Refactor

#96 Issue 89 title추가
  src/app/layout.tsx
Labels: ✨ Feature

#98 Issue 90 Favicon추가
  public/img/harrypoterFavicon.png
  src/app/layout.tsx
Labels: ✨ Feature

#99 Issue 92 vercel analytics 추가
  package-lock.json
  package.json
  src/app/layout.tsx
Labels: ✨ Feature
