Repository f-lab-edu/Find_Your_Character_GPT, pull requests merged in 2023-05, with the labels that each got.

#12 Issue 10 global font 설정
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/StartButton.jsx
  src/styles/globals.css
  src/styles/page.module.css
Labels: ⚙️Setting

#14 버튼 위치 수정
  src/app/page.tsx
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/FloatButton.jsx
  src/components/floatButton/StartButton.jsx
Labels: 🎨 Html&CSS

#13 Issue 9 결과페이지 UI 구현
  public/img/hermione.png
  public/img/potter.png
  public/img/ron.png
  src/app/result/page.jsx
  src/components/contentFont/ContentFont.jsx
  src/components/floatButton/FloatButton.jsx
  src/components/glowText/GlowText.jsx
  src/components/imageBox/ImageBox.jsx
Labels: 🎨 Html&CSS

#20 Issue 16 스테이지 버튼 다이나믹 라우팅 처리
  constant/constants.js
  src/app/page.tsx
  src/app/stage/[slug]/page.jsx
  src/app/stage/page.jsx
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/FloatButton.jsx
  src/components/floatButton/StartButton.jsx
Labels: ✨ Feature, ⚙️Setting

#21 Issue 18 UI 레이아웃 설정
  src/app/layout.tsx
  src/app/result/page.jsx
  src/components/GameDesc/GameDescBox.jsx
  src/components/contentFont/ContentFont.jsx
  src/styles/globals.css
Labels: 🎨 Html&CSS

#23 Issue 15 gpt 연동
  .gitignore
  constant/constants.js
  package-lock.json
  package.json
  src/app/api/generate.jsx
  src/app/page.tsx
  src/app/stage/[slug]/page.jsx
  src/components/floatButton/FloatButton.jsx
  src/pages/api/generate.jsx
Labels: ✨ Feature
