Repository f-lab-edu/Find_Your_Character_GPT, pull requests merged in 2023-06, with the labels that each got.

#26 Issue-24-GPT-시나리오-생성
  src/question.json
Labels: 📄Docs

#29 Issue 28 open ai로 메타데이터 통신
  package-lock.json
  package.json
  src/app/api/generate.jsx
  src/app/layout.tsx
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/FloatButton.jsx
  src/pages/api/generate.jsx
Labels: 📬 API

#34 Issue 32 stage11로 page가 넘어가는 에러
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/FloatButton.jsx
Labels: 🐞 BugFix

#38 Issue 33 FloatButton의 handler함수 분리
  src/components/GameDesc/GameDescBox.jsx
  src/components/floatButton/FloatButton.jsx
Labels: 🔨 Refactor

#40 Issue 39 TypeScript 설정 변경
  tsconfig.json
Labels: ⚙️Setting

#41 Issue 27 GameDescBox, FloatButton, StartButton코드를 TypeScript로 변환
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/components/floatButton/StartButton.tsx
  tsconfig.json
Labels: 🔨 Refactor

#36 Issue 31 공유하기 기능개발
  package-lock.json
  package.json
  public/img/kakao.png
  public/img/link.svg
  src/app/layout.tsx
  src/app/result/page.jsx
  src/components/floatButton/ResultButton.jsx
  src/components/shareModal/ShareModal.jsx
  src/styles/globals.css
Labels: ✨ Feature

#47 Issue 43 open ai 통신으로 응답받기
  src/app/api/generate.jsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/StartButton.tsx
  src/pages/api/generate.jsx
  src/pages/api/generate.tsx
Labels: 📬 API, ✨ Feature

#49 Issue 42 result typescript 변환
  src/app/result/page.tsx
  src/components/floatButton/ResultButton.tsx
  src/components/glowText/GlowText.tsx
  src/components/imageBox/ImageBox.tsx
  src/components/progressBar/ProgressBar.tsx
  src/components/shareModal/ShareModal.tsx
Labels: 🔨 Refactor

#50 Issue 44 loading page 생성
  package-lock.json
  package.json
  src/app/result/page.tsx
  src/components/floatButton/FloatButton.tsx
  src/components/floatButton/ResultButton.tsx
  src/components/glowText/GlowText.tsx
  src/components/loading/Loading.tsx
  src/components/loading/loading.json
Labels: ✨ Feature

#52 Issue 48 stage결과값과 gpt응답값 상태관리
  constant/constants.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/stage/[slug]/page.tsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/pages/api/generate.tsx
  src/question.json
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#56 Issue 55 데이터에 따른 UI 수정
  constant/constants.ts
  public/img/gryffindor.png
  public/img/hufflepuff.png
  public/img/magic.png
  public/img/ravenclaw.png
  public/img/slytherin.png
  src/app/page.tsx
  src/app/result/page.tsx
  src/app/stage/[slug]/page.tsx
  src/components/GameDesc/GameDescBox.tsx
  src/components/floatButton/FloatButton.tsx
  src/question.json
Labels: 🎨 Html&CSS

#61 Issue 58 result 페이지 스크린샷 저장기능
  package-lock.json
  package.json
  public/img/save.svg
  src/app/result/page.tsx
  src/components/shareModal/ShareModal.tsx
Labels: ✨ Feature
